GlobalPlanner:                                  # Also see: http://wiki.ros.org/global_planner

  allow_unknown: false
  default_tolerance: 0.0
  visualize_potential: false
  use_dijkstra: true                            # Use dijkstra's algorithm. Otherwise, A*, default true
  use_quadratic: true                           # Use the quadratic approximation of the potential. Otherwise, use a simpler calculation, default true
  use_grid_path: false                          # Create a path that follows the grid boundaries. Otherwise, use a gradient descent method, default false
  old_navfn_behavior: false                     # Exactly mirror behavior of navfn, use defaults for other boolean parameters, default false
  lethal_cost: 250 #252
  neutral_cost: 50 #60
  cost_factor: 0.8 #0.55
  publish_potential: false
  orientation_mode: 0
  orientation_window_size: 1
  outline_map: false






  
  

