global_costmap:
    plugins:
        - {name: virtual_walls_map, type: "costmap_2d::StaticLayer" }
        - {name: obstacles,  type: "costmap_2d::VoxelLayer" }
        #- {name: sonar,      type: "range_sensor_layer::RangeSensorLayer"}
        - {name: inflation,  type: "costmap_2d::InflationLayer" }
        