local_costmap:
  plugins:
    - {name: virtual_walls_map, type: "costmap_2d::StaticLayer" }
    - {name: voxel,  type: "costmap_2d::VoxelLayer" }
    - {name: inflation,  type: "costmap_2d::InflationLayer" }