local_costmap:
    transform_tolerance: 1.0
    update_frequency: 3.0
    publish_frequency: 3.0
    global_frame: leo_bot/odom
    rolling_window: true
    resolution: 0.05
                                                                                                                                                                                               
    # footprint: [[-0.2875,-0.2875],[-0.2875,0.2875],[0.2875,0.2875],[0.2875,-0.2875]]
    # footprint: [[-0.1575,-0.2875],[-0.1575,0.2875],[0.4375,0.2875],[0.4375,-0.2875]]
    footprint: [[-0.4375,-0.2875],[-0.4375,0.2875],[0.1575,0.2875],[0.1575,-0.2875]]
    footprint_padding: 0.05
    inflation:
      cost_scaling_factor: 2.4 # Exponential rate at which the obstacle cost drops off (default: 10). Must be chosen so that the cost value is > 0 at robot's circumscribed radius.
      inflation_radius: 0.8  # Max. distance from an obstacle at which costs are incurred for planning paths. Must be > robot's circumscribed radius.
    
    width: 10.0
    height: 10.0 
    origin_x: -10.0
    origin_y: -10.0

    plugins:
      - {name: voxel,  type: "costmap_2d::VoxelLayer" }
      - {name: inflation,  type: "costmap_2d::InflationLayer" }
      
      # - {name: social_proxemic_layer,  type: "social_navigation_layers::ProxemicLayer" }
      # - {name: social_passing_layer,  type: "social_navigation_layers::PassingLayer" }