frequency: 20
inputs:
  linear:
    x: AXES_LEFT_Y
  angular:
    z: AXES_RIGHT_X
scales:
  linear:
    x: 1.0
  angular:
    z: 2.0
max_speed: 1.2
min_speed: 0.1
vel_increment: 0.1
layout:
  AXES_LEFT_X:     0
  AXES_LEFT_Y:     1
  AXES_RIGHT_X:    2
  AXES_RIGHT_Y:    3
  BUTTON_TRIANGLE: 0
  BUTTON_CIRCLE:   1
  BUTTON_CROSS:    2
  BUTTON_SQUARE:   3
  BUTTON_L1:       4
  BUTTON_R1:       5
  BUTTON_L2:       6
  BUTTON_R2:       7
  BUTTON_SELECT:   8
  BUTTON_START:    9
  BUTTON_L3:       10
  BUTTON_R3:       11
  AXES_ARROW_LEFT_RIGHT: 4
  AXES_ARROW_UP_DOWN:    5