transform_tolerance: 0.01
min_height: -0.1
max_height: 0.3

angle_min: -0.1 #-1.5708 # -M_PI/2
angle_max: 0.1 #1.5708 # M_PI/2
angle_increment: 0.0087 # M_PI/360.0
scan_time: 0.03333
range_min: 0.0
range_max: 3.0
use_inf: true
target_frame: leo_bot/d455_camera/camera_color_frame
# Concurrency level, affects number of pointclouds queued for processing and number of threads used
# 0 : Detect number of cores
# 1 : Single threaded
# 2->inf : Parallelism level
concurrency_level: 12