topics_glob: "[*]"  # "" nothing, "[/rosout, etc]" specified, "[*]" all
services_glob: "[*]" # "" nothing, "[/rosout, etc]" specified, "[*]" all
params_glob: "" # "" nothing, "[/rosout, etc]" specified, "[*]" all
