authenticate: false

port: 9090
address: 0.0.0.0

retry_startup_delay: 5
fragment_timeout: 600
delay_between_messages: 0
max_message_size: "None"
unregister_timeout: 10
use_compression: false

websocket_ping_interval: 0
websocket_ping_timeout: 30
websocket_external_port: "None"

bson_only_mode: false
